### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by newmen** [moumar/ruby-mp3info#10]
Hello.
When I editing some song with cp1251 encoding tags to set new tags on utf-8, then I have this error:

ruby-1.9.2-p290/gems/ruby-mp3info-0.6.16/lib/mp3info/id3v2.rb:283:in `block (2 levels) in to_bin': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

May be I doing something wrong?

**Comment by dan** [comment]
We still see this error when adding chapters using 0.8.10.

**Comment by dan** [comment]
Bump. We still cannot use chapters.
