### ISSUE TITLE
Length (duration) incorrect on certain MP3s

### ISSUE THREAD

**Issue by jcraigk** [moumar/ruby-mp3info#42]
When detecting length (duration) on a certain set of mp3 files, incorrect duration is returned.  For example, on a 467 second mp3, 683 seconds is reported.  It seems durations are being inflated by approx 40% across these mp3s.  These were created from FLAC sources using ffmpeg as in:

ffmpeg -i source.flac -aq 0 "destination.mp3"

Here is the information returned by the gem on an mp3 that is actually 467 seconds in length (id3 tags omitted):

MPEG 1 Layer 3 VBR 160 Kbps JStereo 44100 Hz length 683.0984000000001 sec. header {:layer=>3, :bitrate=>160, :samplerate=>44100, :mpeg_version=>1, :padding=>false, :size=>522, :error_protection=>false, :private=>true, :mode_extension=>0, :copyright=>false, :original=>true, :emphasis=>0, :channel_num=>1, :channel_mode=>"JStereo"}

I've used the gem in many other cases for pre-made mp3s and the length is reported correctly; this is the first I have encountered this issue.  Is there something wrong with my mp3s?  Are they incompatible with this gem?

**Comment by quinn** [comment]
@moumar any thoughts on this? I'm experiencing the same issue on v0.8.5, but the mp3 is ~ 30 minutes longer than reported length (opposite problem of OP)

**Comment by quinn** [comment]
@zenmatt @jcraigk do you know of a workaround
