### ISSUE TITLE
License is incorrect in published gem specification

### ISSUE THREAD

**Issue by malmckay** [moumar/ruby-mp3info#48]
Hi,
The specification in the gem on rubygems.org specifies the MIT license, where as the gem spec specifies GPLv3

> wget https://rubygems.org/downloads/ruby-mp3info-0.8.5.gem
> gem spec ruby-mp3info-0.8.5.gem|grep -A1 license
licenses:
- MIT

Fixing this would be helpful for ppl who use an automated License checker,
Thanks!
Mal

**Comment by moumar** [comment]
fixed in v0.8.6
