### ISSUE TITLE
id3v1 genres on id3v2.3 and id3v2.4 tags

### ISSUE THREAD

**Issue by jameswyper** [moumar/ruby-mp3info#50]
Hi

I've just started using mp3info on a project of mine.  I have a number of mp3 files with id3v2.3 or id3v2.4 tags that have the genre following the old (id3v1) format ie TCON == "(8)" (for Jazz)

Looking at the specs on id3.org it appears that for id3v2.3 this is valid as an alternative to the actual genre, for id3v2.4 having the number without brackets (e.g. "8") is valid although my id3v2.4 tags have the number in brackets.  I can't remember which program created these files but it means that there must be programs out there not following the standard precisely and it would be good to handle these.

I've forked your repository and have made a small change to the code  - currently it looks up the genre number for TCO tags of the format ^\((\d+)\)$, which I've changed to TCO or TCON tags with this format, or TCON tags of the format ^\(d+)$

However I'm not sure how to replace the version of mp3info I've already installed on my machine via gem with my new version so that I can test it more before submitting a pull request 

running "rake test" on my code runs the tests OK but "sudo rake install" doesn't work (no "install" target found).  Can you advise me what I need to do to make my code pick up my version of mp3info rather than the one installed via gem?

Once I've tested this properly I'll create a pull request.

Thanks
James

**Comment by moumar** [comment]
hi James,

did you try "rake install_gem" ? you can have the rake tasks list with "rake -T"

best regards

**Comment by jameswyper** [comment]
Thanks - that was the information I was missing! (I'm not at all familiar with rake and packaging).  I've tried that and it seems to have worked.  Will let you know how testing goes.

**Comment by jameswyper** [comment]
Testing seems OK, please consider merging my changes

Thanks

**Comment by moumar** [comment]
thanks for this patch.
