### ISSUE TITLE
Test fails for ruby-mp3info-0.8.7 with ruby 2.2.x

### ISSUE THREAD

**Issue by graaff** [moumar/ruby-mp3info#58]
With ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux] I'm seeing the following test failure:

```
  1) Error:
Mp3InfoTest#test_id3v2_get_pictures:
TypeError: no implicit conversion from nil to integer
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/lib/mp3info/id3v2.rb:318:in `[]'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/lib/mp3info/id3v2.rb:318:in `block in pictures'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/lib/mp3info/id3v2.rb:282:in `each_index'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/lib/mp3info/id3v2.rb:282:in `pictures'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/test/test_ruby-mp3info.rb:218:in `block in test_id3v2_get_pictures'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/lib/mp3info.rb:304:in `open'
    /var/tmp/portage/dev-ruby/ruby-mp3info-0.8.7/work/ruby22/ruby-mp3info-0.8.7/test/test_ruby-mp3info.rb:217:in `test_id3v2_get_pictures'
```

I also noticed that travis.yml contains two references to ruby 2.1, but none to ruby 2.2, I'm not sure that was intended.

**Comment by testbrian** [comment]
any ideas @ekaminsky?

**Comment by ekaminsky** [comment]
Hmm, not happening for me.  Just opened a new terminal, cloned the git repo to a brand new directory, switched to ruby 2.2.2p95 (same revision and x86_64-linux), ran `test/test_ruby-mp3info.rb`, no issues. Could I be doing something wrong?

**Comment by graaff** [comment]
I've tried to reproduce this to get some more information, but all tests now pass for me as well, so this can probably be closed.

May still be useful to include ruby 2.2 in travis.yml rather than two ruby 2.1 versions.

**Comment by testbrian** [comment]
:+1:
