### ISSUE TITLE
TypeError: no implicit conversion from nil to integer

### ISSUE THREAD

**Issue by ricale** [moumar/ruby-mp3info#69]
I got error when executing code below.

    file_names = Dir["#{Rails.root}/public/musics/**/*.mp3"]

    file_names.each do |file_name|
      puts "#{file_name}:"
      Mp3Info.open("#{file_name}") do |mp3|
        tag2 = mp3.tag2
        pictures = tag2.pictures              # ERROR here
        pictures.each do |description, data|
          puts "#{description}"
        end
      end
    end

below is error messages I got.

    TypeError: no implicit conversion from nil to integer
	from /Users/ricale/.rvm/gems/ruby-2.3.3/gems/ruby-mp3info-0.8.10/lib/mp3info/id3v2.rb:312:in `[]'
	from /Users/ricale/.rvm/gems/ruby-2.3.3/gems/ruby-mp3info-0.8.10/lib/mp3info/id3v2.rb:312:in `block in pictures'
	from /Users/ricale/.rvm/gems/ruby-2.3.3/gems/ruby-mp3info-0.8.10/lib/mp3info/id3v2.rb:275:in `each_index'
	from /Users/ricale/.rvm/gems/ruby-2.3.3/gems/ruby-mp3info-0.8.10/lib/mp3info/id3v2.rb:275:in `pictures'

error occurred with [this mp3 file (google drive link)](https://drive.google.com/open?id=0Bx-lHgoosiWXUGV1VXFEN2FVdkU)

environments:
- ruby 2.3.3
- ruby-mp3info 0.8.10

thanks

**Comment by ricale** [comment]
I fixed https://github.com/moumar/ruby-mp3info/blob/master/lib/mp3info/id3v2.rb#L280 like below and worked fine.

    jpg_regexp = Regexp.new("jpg|JPG|jpeg|JPEG|jfif|JFIF".force_encoding("BINARY"), # add |jfif|JFIF

**Comment by moumar** [comment]
thanks for this patch :) fixed in 3ecddf9c8a222d37c03361cb213231bd48f58a2e
